// <auto-generated />
using AspNetCoreIdentityServer4Persistence.ConfigurationStore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace AspNetCoreIdentityServer4.Migrations
{
    [DbContext(typeof(ConfigurationStoreContext))]
    [Migration("20171224145139_id4configMigration")]
    partial class id4configMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("AspNetCoreIdentityServer4Persistence.ConfigurationStore.ApiResourceEntity", b =>
                {
                    b.Property<string>("ApiResourceName")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApiResourceData");

                    b.HasKey("ApiResourceName");

                    b.ToTable("ApiResources");
                });

            modelBuilder.Entity("AspNetCoreIdentityServer4Persistence.ConfigurationStore.ClientEntity", b =>
                {
                    b.Property<string>("ClientId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientData");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("AspNetCoreIdentityServer4Persistence.ConfigurationStore.IdentityResourceEntity", b =>
                {
                    b.Property<string>("IdentityResourceName")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("IdentityResourceData");

                    b.HasKey("IdentityResourceName");

                    b.ToTable("IdentityResources");
                });
#pragma warning restore 612, 618
        }
    }
}
